FROM alpine
LABEL application=jenkins

RUN apk add --no-cache python3-dev musl-dev libffi-dev openssl-dev gcc bash git make coreutils curl
RUN curl -fs -L https://download.docker.com/linux/static/stable/x86_64/docker-19.03.8.tgz | tar xvfz - --strip-components 1 -C /usr/local/bin docker/docker
RUN pip3 install docker-compose
