version: '2.4'

volumes:
  jenkins-data:
    external: true
  jenkins-docker-certs:
    driver: local

services:
  docker:
    build:
      context: .
      dockerfile: Dockerfile.dind
    privileged: true
    healthcheck:
      test: docker ps -q
      interval: 3s
      retries: 10
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - 2376:2376
  jenkins:
    image: jenkinsci/blueocean
    depends_on:
      docker:
        condition: service_healthy
      ngrok:
        condition: service_healthy
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    ports:
      - 8080:8080
  ngrok:
    build:
      context: .
      dockerfile: Dockerfile.ngrok
    healthcheck:
      test: curl -fs localhost:4040
      interval: 3s
      retries: 10
    command:
      - ngrok
      - http
      - jenkins:8080
      - --hostname=cd-docker-jenkins.ngrok.io
      - --log=stdout
      - --authtoken=${NGROK_AUTH_TOKEN}
      - --inspect=false
      - --bind-tls=true
  agent:
    image: continuousdeliverydocker/docker-agent
    build:
      context: .
      dockerfile: Dockerfile.agent
      args:
        DOCKER_VERSION: 19.03.8
