FROM alpine
LABEL application=jenkins
ARG DOCKER_VERSION

RUN apk add --no-cache python3-dev musl-dev libffi-dev openssl-dev gcc bash git make coreutils curl && \
    apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing hub
RUN curl -fs -L https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz | tar xvfz - --strip-components 1 -C /usr/local/bin docker/docker
RUN pip3 install docker-compose
